### ISSUE TITLE
Some additional info

### ISSUE THREAD

**Issue by hsugoken** [NSEDownload/NSEDownload#4]
Hi first of all this one's a great work so far that I have seen for getting NSE data. Thank you for this.
I wanted to ask few things:
1.  Is there any separate documentation that you've created for this?
2. Can it get data for other time frames apart from daily data like minutes or hours?
3.  Can it get options data for nifty bank or other shares?

**Comment by jinit24** [comment]
Thanks man. To answer your questions 
1. The Readme is the only documentation for the time being. It describes the usage. Let me know what things are you unable to get, I'll add those it.
2. Minutes or hours will not be possible because this just scrapes data and I don't think nse stores that data. ( Or I wasn't able to find it)
3. I haven't added data for options. Maybe I can do this.

Let me know your suggestions.

**Comment by hsugoken** [comment]
Okay so this is collecting data from the NSE website then.
I'll also look into other things if I can contribute there.
