### ISSUE TITLE
Adjusted Data

### ISSUE THREAD

**Issue by maheshgune** [NSEDownload/NSEDownload#7]
May I know till what date in the past, data is adjusted.

It seems it is adjusted after 2009/2010. 

A correct date will help while taking data for back-testing.

Thanks.

**Comment by jinit24** [comment]
All events after 2010.

**Comment by bhavesh0009** [comment]
Is it possible to get adjusted values before 2010 as well?

**Comment by bhavesh0009** [comment]
It looks M&M is not adjusted in March-2010
![image](https://user-images.githubusercontent.com/28176923/150629657-519f1d7d-0946-4e0e-91bf-91043d73a8d7.png)

**Comment by jinit24** [comment]
Hi @bhavesh0009,
I just checked, and the events are adjusted after May 2010. So, the NSE website allows searching for specific events like splits and bonus only after May 2010. I am currently using this. 
Otherwise, you can also get a dump of all events. Finding splits and bonuses from it might be tricky. I'll definitely take a look. I'll have to make some changes to use this, 

As someone else suggested, a dump can be taken from moneycontrol or other sites for such static data. (Data before 2010). This another option.

Let me know your thoughts.
